name: semantic release

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'If you are sure to launch a new release, put the value to true.'
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write
  statuses: write

jobs:
  semantic-release:
    if: github.event.inputs.prompt == 'true'
    uses: benbenbang/tombo/.github/workflows/reusable-sr.yml@workflows
    secrets: inherit

  update-release-title:
    runs-on: ubuntu-latest
    needs: semantic-release
    if: ${{ needs.semantic-release.outputs.new_release != null }}
    steps:
      - uses: actions/checkout@v4
      - name: update github release
        run: |
          gh release edit -R ${{ github.repository }} --title "ðŸ§½ Tombo ${{ needs.semantic-release.outputs.new_release_tag }}" "${{ needs.semantic-release.outputs.new_release_tag }}"
        env:
          GH_TOKEN: ${{ github.token }}
